logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    fr.perpetualmotion.airbnbback: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: airbnb-back
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url:  jdbc:postgresql://localhost:5432/airbnb
    username: 'postgres'
    password: '4ishAhpa'
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: airbnb
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: airbnb
    enabled: true
  #    drop-first: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8080

okta:
  oauth2:
    issuer: https://dev-xqx8k2h52vf0lqrn.us.auth0.com/
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}

application:
  auth0:
    role-landlord-id: rol_USOG172Q4NKLaWJu